### ISSUE TITLE
[Dicarina] [Sidekiq - Worker] UpdateQualifierPromotionsWorker - Accion Preventiva

### ISSUE THREAD

**Issue by asantamaria20** [ubiqua/sidekiq_alerts#1]
###Contexto
En la ultima semana hemos tenido más usuarios consultando por la visibilidad de las ofertas en AVE luego del ultimo corte a las 5:30pm inicia una actualización de las ultimas promociones creadas en donde se debe reflejar luego de las 7:30pm

https://dicarina-ave.herokuapp.com/sidekiq/recurring-jobs

Seria este: Scheduled::UpdateQualifierPromotionsWorker

Seria posible que esto se ejecute con mayor frecuencia?

**Comment by jecsham** [comment]
### TBD

Se debe realizar el cambio a nivel de variables de ambiente:
![image](https://user-images.githubusercontent.com/10292582/139076108-3f972fd6-3730-493f-bf30-f0f12bd7a107.png)
La frecuencia de actualización actual es de `1h`.
- Se cambiará la frecuencia a `30m`.

Este cambio se debe de realizar fuera de horas laborales ya que puede requerir reinicio de los dynos.
